### ISSUE TITLE
单卡训练正常，多卡训练报错noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0 RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by TonyAlpha12** [haoran1062/yolov3#2]
大佬，我也遇到你类似的问题了，你是怎么解决的？
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 377, in <module>
    trainer.run()
  File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 86, in run
    self.train(epoch)
  File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 106, in train
    scnn_seg_pred, scnn_exist_pred, yolo_outputs, seg_loss, exist_loss, yolo_total_loss, multi_loss = self.model(imgs, seg_targets, od_targets)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzc/pytorch_yolov3_old/models/adnet.py", line 22, in forward
    yolo_total_loss, yolo_outputs = self.yolo(x, scnn_route_1, yolo_route_2, yolo_target)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzc/pytorch_yolov3_old/models/decoder/yolov3_decoder.py", line 238, in forward
    yolo_13_out, yolo_13_loss = self.yolo_13(yolo_13_pred, yolo_target, self.img_dim)
  File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzc/pytorch_yolov3_old/models/decoder/yolov3_decoder.py", line 122, in forward
    ignore_thres=self.ignore_thres,
  File "/home/yzc/pytorch_yolov3_old/utils/utils.py", line 347, in my_build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered

**Comment by haoran1062** [comment]
if you use dataparallel to train your model with multi-GPU, turn to use DistributedDataParallel you can fix it

**Comment by TonyAlpha12** [comment]
直接把dataparallel换成DistributedDataParallel就行了？好的，我试一下




| |
13767142364
|
|
邮箱：13767142364@163.com
|

Signature is customized by Netease Mail Master

在2019年12月04日 10:06，haoran1062 写道：

if you use dataparallel to train your model with multi-GPU, turn to use DistributedDataParallel you can fix it

**Comment by haoran1062** [comment]
> 大佬，我也遇到你类似的问题了，你是怎么解决的？
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> Traceback (most recent call last):
> File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in
> main(ptvsdArgs)
> File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/**main**.py", line 432, in main
> run()
> File "/home/yzc/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/**main**.py", line 316, in run_file
> runpy.run_path(target, run_name='**main**')
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 377, in
> trainer.run()
> File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 86, in run
> self.train(epoch)
> File "/home/yzc/pytorch_yolov3_old/unified_train.py", line 106, in train
> scnn_seg_pred, scnn_exist_pred, yolo_outputs, seg_loss, exist_loss, yolo_total_loss, multi_loss = self.model(imgs, seg_targets, od_targets)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
> outputs = self.parallel_apply(replicas, inputs, kwargs)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
> return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
> output.reraise()
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in replica 0 on device 0.
> Original Traceback (most recent call last):
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
> output = module(*input, **kwargs)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/yzc/pytorch_yolov3_old/models/adnet.py", line 22, in forward
> yolo_total_loss, yolo_outputs = self.yolo(x, scnn_route_1, yolo_route_2, yolo_target)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/yzc/pytorch_yolov3_old/models/decoder/yolov3_decoder.py", line 238, in forward
> yolo_13_out, yolo_13_loss = self.yolo_13(yolo_13_pred, yolo_target, self.img_dim)
> File "/home/yzc/.conda/envs/dl_cai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/yzc/pytorch_yolov3_old/models/decoder/yolov3_decoder.py", line 122, in forward
> ignore_thres=self.ignore_thres,
> File "/home/yzc/pytorch_yolov3_old/utils/utils.py", line 347, in my_build_targets
> noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
> RuntimeError: CUDA error: device-side assert triggered

I found that if you use DataParallel(DP), all data 

> 直接把dataparallel换成DistributedDataParallel就行了？好的，我试一下 | | 13767142364 | | 邮箱：13767142364@163.com | Signature is customized by Netease Mail Master 在2019年12月04日 10:06，haoran1062 写道： if you use dataparallel to train your model with multi-GPU, turn to use DistributedDataParallel you can fix it — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yeah, I found that if you use DataParallel(DP), data is always on device:0, when computing multi-GPU loss, the loss data may at each own device, so you will compute two device's data that "RuntimeError: CUDA error: device-side assert triggered" occured, but if you use DistributedDataParallel, every device have their own data, of course, this is only my opinion😂

**Comment by TonyAlpha12** [comment]
大佬，这个分布式具体你是怎么用的。在哪里加什么代码呢？

**Comment by haoran1062** [comment]
> 大佬，这个分布式具体你是怎么用的。在哪里加什么代码呢？

reference to main.py
define your ADD and PORT, init distributed group, and DDP(your model)
```
os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '9999'
dist.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:9999', world_size=1, rank=0)
......
yolo_p = nn.parallel.DistributedDataParallel(yolo, device_ids=train_config['gpu_ids'])
```
also you can use Nvidia apex fp16 DDP, this is better than pytorch's DDP(I think)

**Comment by TonyAlpha12** [comment]
os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '9999'
torch.distributed.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:9999', world_size=1, rank=0)

# prepare model
if torch.cuda.device_count() > 1:
    self.model.cuda()
    self.model = torch.nn.parallel.DistributedDataParallel(self.model)
按你说的设置了，还是报原来的错误。我用VScode来Debug的时候，发现数据还是会在两张卡里切换

**Comment by haoran1062** [comment]
> os.environ['MASTER_ADDR'] = '127.0.0.1'
> os.environ['MASTER_PORT'] = '9999'
> torch.distributed.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:9999', world_size=1, rank=0)
> 
> # prepare model
> if torch.cuda.device_count() > 1:
> self.model.cuda()
> self.model = torch.nn.parallel.DistributedDataParallel(self.model)
> 按你说的设置了，还是报原来的错误。我用VScode来Debug的时候，发现数据还是会在两张卡里切换

so where did you encode your data? in model or main? if in model maybe you can try to(device)? I can not see your codes, Different implementation may occurred different error💔

**Comment by TonyAlpha12** [comment]
self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
def run(self):
        # prepare model
        if torch.cuda.device_count() > 1:
            
            self.model.to(self.device)
            self.model = torch.nn.parallel.DistributedDataParallel(self.model)
            # self.model = torch.nn.DataParallel(self.model, device_ids=[0, 1]).cuda(self.device)
            # cudnn.benchmark = True
        
        if self.args.resume:
            save_dict = torch.load(self.args.resume)
            if isinstance(self.model, torch.nn.DataParallel):
                self.model.module.load_state_dict(save_dict['net'])
            else:
                self.model.load_state_dict(save_dict['net'])

        # self.model.cuda(self.device)
        for epoch in range(1, self.config['epochs'] + 1):
            # train
            self.train(epoch)

def train(self, epoch):
        print('Start training! Train Epoch:{}'.format(epoch))
        self.model.train()
        self.train_loader = self.get_dataset(self.train_path)
        multi_loss = 0
        progressbar = tqdm(range(len(self.train_loader)))

        # start training
        for batch_i, (_, imgs, od_targets, seg_targets) in enumerate(self.train_loader):
            batches_done = len(self.train_loader) * epoch + batch_i
            imgs = Variable(imgs).to(self.device)
            od_targets = Variable(od_targets).to(self.device)
            seg_targets = Variable(seg_targets).to(self.device).long()
            self.optimizer.zero_grad()

**Comment by haoran1062** [comment]
> self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
> def run(self):
> # prepare model
> if torch.cuda.device_count() > 1:
> 
> ```
>         self.model.to(self.device)
>         self.model = torch.nn.parallel.DistributedDataParallel(self.model)
>         # self.model = torch.nn.DataParallel(self.model, device_ids=[0, 1]).cuda(self.device)
>         # cudnn.benchmark = True
>     
>     if self.args.resume:
>         save_dict = torch.load(self.args.resume)
>         if isinstance(self.model, torch.nn.DataParallel):
>             self.model.module.load_state_dict(save_dict['net'])
>         else:
>             self.model.load_state_dict(save_dict['net'])
> 
>     # self.model.cuda(self.device)
>     for epoch in range(1, self.config['epochs'] + 1):
>         # train
>         self.train(epoch)
> ```
> 
> def train(self, epoch):
> print('Start training! Train Epoch:{}'.format(epoch))
> self.model.train()
> self.train_loader = self.get_dataset(self.train_path)
> multi_loss = 0
> progressbar = tqdm(range(len(self.train_loader)))
> 
> ```
>     # start training
>     for batch_i, (_, imgs, od_targets, seg_targets) in enumerate(self.train_loader):
>         batches_done = len(self.train_loader) * epoch + batch_i
>         imgs = Variable(imgs).to(self.device)
>         od_targets = Variable(od_targets).to(self.device)
>         seg_targets = Variable(seg_targets).to(self.device).long()
>         self.optimizer.zero_grad()
> ```

I have no idea why you still have this error occurred, I only remember I was use DDP instead of use DP to fix this bug😥

**Comment by TonyAlpha12** [comment]
> > self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
> > def run(self):
> > # prepare model
> > if torch.cuda.device_count() > 1:
> > ```
> >         self.model.to(self.device)
> >         self.model = torch.nn.parallel.DistributedDataParallel(self.model)
> >         # self.model = torch.nn.DataParallel(self.model, device_ids=[0, 1]).cuda(self.device)
> >         # cudnn.benchmark = True
> >     
> >     if self.args.resume:
> >         save_dict = torch.load(self.args.resume)
> >         if isinstance(self.model, torch.nn.DataParallel):
> >             self.model.module.load_state_dict(save_dict['net'])
> >         else:
> >             self.model.load_state_dict(save_dict['net'])
> > 
> >     # self.model.cuda(self.device)
> >     for epoch in range(1, self.config['epochs'] + 1):
> >         # train
> >         self.train(epoch)
> > ```
> > 
> > 
> > def train(self, epoch):
> > print('Start training! Train Epoch:{}'.format(epoch))
> > self.model.train()
> > self.train_loader = self.get_dataset(self.train_path)
> > multi_loss = 0
> > progressbar = tqdm(range(len(self.train_loader)))
> > ```
> >     # start training
> >     for batch_i, (_, imgs, od_targets, seg_targets) in enumerate(self.train_loader):
> >         batches_done = len(self.train_loader) * epoch + batch_i
> >         imgs = Variable(imgs).to(self.device)
> >         od_targets = Variable(od_targets).to(self.device)
> >         seg_targets = Variable(seg_targets).to(self.device).long()
> >         self.optimizer.zero_grad()
> > ```
> 
> I have no idea why you still have this error occurred, I only remember I was use DDP instead of use DP to fix this bug😥

继续用DataParallel，改了改可以跑起来了，但是一跑到最后一个batch，就又报原来的错了，真是醉了。

**Comment by TonyAlpha12** [comment]
> > self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
> > def run(self):
> > # prepare model
> > if torch.cuda.device_count() > 1:
> > ```
> >         self.model.to(self.device)
> >         self.model = torch.nn.parallel.DistributedDataParallel(self.model)
> >         # self.model = torch.nn.DataParallel(self.model, device_ids=[0, 1]).cuda(self.device)
> >         # cudnn.benchmark = True
> >     
> >     if self.args.resume:
> >         save_dict = torch.load(self.args.resume)
> >         if isinstance(self.model, torch.nn.DataParallel):
> >             self.model.module.load_state_dict(save_dict['net'])
> >         else:
> >             self.model.load_state_dict(save_dict['net'])
> > 
> >     # self.model.cuda(self.device)
> >     for epoch in range(1, self.config['epochs'] + 1):
> >         # train
> >         self.train(epoch)
> > ```
> > 
> > 
> > def train(self, epoch):
> > print('Start training! Train Epoch:{}'.format(epoch))
> > self.model.train()
> > self.train_loader = self.get_dataset(self.train_path)
> > multi_loss = 0
> > progressbar = tqdm(range(len(self.train_loader)))
> > ```
> >     # start training
> >     for batch_i, (_, imgs, od_targets, seg_targets) in enumerate(self.train_loader):
> >         batches_done = len(self.train_loader) * epoch + batch_i
> >         imgs = Variable(imgs).to(self.device)
> >         od_targets = Variable(od_targets).to(self.device)
> >         seg_targets = Variable(seg_targets).to(self.device).long()
> >         self.optimizer.zero_grad()
> > ```
> 
> I have no idea why you still have this error occurred, I only remember I was use DDP instead of use DP to fix this bug😥

在yolov3计算偏移的地方加这个代码就不会报错了。超出索引问题我估计是backbone没有预训练过，所以gj、gi很容易超出边界，只要把它限制一下就可以了。
# ============ M ================
    b = b % nB

    gx, gy = gxy.t()
    gw, gh = gwh.t()
    gi, gj = gxy.long().t()

    # ============ M ================
    gi[gi < 0] = 0
    gj[gj < 0] = 0
    gi[gi >= nGW] = nGW - 1
    gj[gj >= nGH] = nGH - 1
    # ============ M ================
